[package]
name = "ctloader"
version = "0.1.0"
authors = ["Ken Youens-Clark <kyclark@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "~0.15"
clap = "~2.33"
# quick-xml = "0.21.0"
# serde = "~1.0"
serde = { version = "1.0", features = [ "derive" ] }
quick-xml = { version = "0.21.0", features = [ "serialize" ] }
spectral = "0.6.0"
diesel = { version = "1.4.5", features = ["postgres"] }
