// Generated by diesel_ext
//

use crate::schema::study;

//#[derive(Queryable, Debug, Identifiable)]
//#[primary_key(study_id)]
//pub struct Study {
//    pub study_id: i32,
//    pub nct_id: String,
//}

#[derive(Queryable, Debug, Identifiable)]
#[table_name = "study"]
#[primary_key(study_id)]
pub struct DbStudy {
    pub study_id: i32,
    pub nct_id: String,
}

#[derive(Insertable, Debug)]
#[table_name = "study"]
pub struct DbNewStudy<'a> {
    pub nct_id: &'a str,
}
